spring.application.name=nagoyameshi

# --- DB接続設定---
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/nagoyameshi_db
spring.datasource.username=root
spring.datasource.password=sannta1231
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# schema.sql / data.sqlを起動のたびに実行する
spring.sql.init.encoding=utf-8
spring.sql.init.mode=always

# 店舗画像アップロード用
spring.servlet.multipart.max-file-size=5MB

# 開発中はThymeleafのキャッシュを無効化（テンプレート変更を即反映）
spring.thymeleaf.cache=false

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=25a85cadf8cb5b
spring.mail.password=11498e7b36fcd4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true