spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mail.host=${MAILGUN_SMTP_SERVER}
spring.mail.port=${MAILGUN_SMTP_PORT}
spring.mail.username=${MAILGUN_SMTP_LOGIN}
spring.mail.password=${MAILGUN_SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

stripe.api-key=${STRIPE_API_KEY}
stripe.publishable-key=${STRIPE_PUBLISHABLE_KEY}
stripe.premium-plan-id=${STRIPE_PREMIUM_PLAN_ID}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
