CREATE TABLE IF NOT EXISTS users(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	enabled BOOLEAN NOT NULL,
	subscriber BOOLEAN NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shops(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	category_id INT NOT NULL,
	admin_id INT NOT NULL,
	name VARCHAR(50) NOT NULL,
	address VARCHAR(255) NOT NULL,
	image_name VARCHAR(255),
	description VARCHAR(255) NOT NULL,
	opening_time TIME NOT NULL,
	closing_time TIME NOT NULL,
	lowest_price INT NOT NULL,
	highest_price INT NOT NULL,
	seating_capacity INT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (category_id) REFERENCES category (id),
	FOREIGN KEY (admin_id) REFERENCES admin (id)
);